[WIP] update style: modified from var to let/const
Gsantomaggio/amqplib pull request #1
Opened 2022-05-17 09:39 UTC by aleattene

2022-05-17 11:13 UTC, Gsantomaggio commented
@micheleriva WDYT?

2022-05-17 16:27 UTC, aleattene commented
Now everything should work, send_stream and receive_stream.

2022-05-23 09:20 UTC, micheleriva requested changes

2022-05-23 09:20 UTC, micheleriva commented on examples/stream_queues/receive_stream.js
> +async function receiveStream() { //=====================================================================================
@aleattene what's the `//=====================================================================================` comment for? Can we get rid of that?

2022-05-23 09:20 UTC, micheleriva commented on examples/stream_queues/receive_stream.js
> +        process.once('SIGINT', () => { conn.close(); });
We can get rid of the curly braces around `conn.close();` here

2022-05-23 09:20 UTC, micheleriva commented on examples/stream_queues/receive_stream.js
> +        const ch = await conn.createChannel();
Please use an explicative variable name `ch -> channel`

2022-05-23 09:20 UTC, micheleriva commented on examples/stream_queues/receive_stream.js
> +        const q = 'my_first_stream';
Please use an explicative variable name `q -> queue`

2022-05-23 09:20 UTC, micheleriva commented on examples/stream_queues/receive_stream.js
> +//======================================================================================================================
Is that comment necessary?

2022-05-23 09:20 UTC, micheleriva commented on examples/stream_queues/send_stream.js
> +async function sendStream () { //=======================================================================================
Is that comment necessary?

2022-05-23 09:20 UTC, micheleriva commented on examples/stream_queues/send_stream.js
> +        const conn = await amqp.connect('amqp://localhost');
Please use an explicative variable name `conn -> connection`

2022-05-23 09:20 UTC, micheleriva commented on examples/stream_queues/send_stream.js
> +        const ch = await conn.createChannel();
Please use an explicative variable name `ch -> channel`

2022-05-23 09:20 UTC, micheleriva commented on examples/stream_queues/send_stream.js
> +        const q = 'my_first_stream';
Please use an explicative variable name `q -> queue`

2022-05-23 09:20 UTC, micheleriva commented on examples/stream_queues/send_stream.js
> +        const conn = await amqp.connect('amqp://localhost');
Also, don't you need the `process.once('SIGINT', conn.close);` control here?

2022-05-23 09:20 UTC, micheleriva commented on examples/stream_queues/receive_stream.js
> +        process.once('SIGINT', () => { conn.close(); });
You can use the shorthand:

`process.once('SIGINT', conn.close);`

2022-05-23 09:28 UTC, aleattene commented on examples/stream_queues/receive_stream.js
> +async function receiveStream() { //=====================================================================================
Yes we can.

2022-05-23 09:31 UTC, aleattene commented on examples/stream_queues/receive_stream.js
> +//======================================================================================================================
Only for my personal greater readability. 
Unnecessary. I remove it.

2022-05-23 11:47 UTC, aleattene commented on examples/stream_queues/send_stream.js
> +async function sendStream () { //=======================================================================================
Unnecessary. I remove it.

2022-05-23 11:51 UTC, aleattene commented on examples/stream_queues/send_stream.js
> +        const conn = await amqp.connect('amqp://localhost');
Right. Control added. Thanks.

2022-05-23 12:20 UTC, Gsantomaggio commented
@aleattene @micheleriva going to merge. Thank you both!

2022-05-23 12:20 UTC, merged